# Generated by Django 5.1.1 on 2024-10-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Blog", "0002_alter_student_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="batch_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="batch",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
